### ISSUE TITLE
Provide some example on how to use this lib

### ISSUE THREAD

**Issue by JoanComasFdz** [MNie/AppInsights.Enricher#2]
Hi,

Could you please provide some real world example on how this library may be used to enrich telemetry?

For example does this allow to enrich an SQLClient trace? or from EntityFramework?

Thanks

**Comment by MNie** [comment]
Hi, @JoanComasFdz I wrote some time ago a post about it which you could find [here](https://www.mnie.me/appinsightslogging). Regards enriching SQL trace it should be logged to AppInsights and you could add your custom dimensions there.

**Comment by JoanComasFdz** [comment]
Ah perfect, thanks a lot!

It would be great if could add this link to the readme.MD :)

**Comment by MNie** [comment]
@JoanComasFdz I added a note at the bottom of the readme [via this](https://github.com/MNie/AppInsights.Enricher/commit/e0181998f0c6a6242b72fdc9c8426b9ee6cd4583). Thanks : )
